# Generated by Django 4.2.6 on 2023-10-20 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicao', models.DateTimeField(default=datetime.datetime(2023, 10, 20, 14, 15, 35, 429652))),
            ],
        ),
    ]
